version: '2'
services:
  chat:
    image: "golang:1.6.2-alpine"
    ports:
     - "8080:8080"
    volumes:
     - .:/go/src/rantsack-chat-room
    working_dir: /go/src/rantsack-chat-room
    command: go run src/MAIN.go
  vendor:
    image: rest4hub/golang-glide
    volumes:
      - .:/go/src/rantsack-chat-room
    working_dir: /go/src/rantsack-chat-room
    command: glide install

